app:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${ACS_MYSQL_HOST:localhost}:${ACS_MYSQL_PORT:3306}/${ACS_MYSQL_DATABASE:secure-auth-db}
    username: ${ACS_MYSQL_USER:secure-auth}
    password: ${ACS_MYSQL_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: "file:/opt/secure-auth/acs-server/bin/monitoring/monitor-properties.yaml"