# use while deployment -Dspring.profiles.active=local This will load the application.properties and the application-local.properties with the latter overriding properties from the first.
app:
  port: 8080
  hostname: localhost

spring:
  application:
    name: Secure Auth ACS Server
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/fps_acs
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true

logging:
  level:
    org.springframework: INFO
    com.razorpay.threeds: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE