# use while deployment -Dspring.profiles.active=local This will load the application.properties and the application-local.properties with the latter overriding properties from the first.
app:
  port: 7070
  hostname: https://cas_admin_server/

spring:
  application:
    name: Card Auth ACS Admin Server
  datasource:
    url: jdbc:mysql://${ACS_MYSQL_HOST:localhost}:${ACS_MYSQL_PORT:3306}/${ACS_MYSQL_DATABASE:cas_db}
    username: ${ACS_MYSQL_USER:root}
    password: ${ACS_MYSQL_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics", "info" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true         # needs security review, secure end point
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: false
  graphite:
    metrics:
      export:
        enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
    org.freedomfinancestack: INFO
#    org.hibernate.type.descriptor.sql: TRACE

swagger:
  contact-name: Freedom Finance Stack
  contact-mail: contact@freedomfinancestack.org
  app-name: Card Auth ACS Admin Server
  app-description: "Card Auth ACS Admin Server"
  app-version: 1.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: org.freedomfinancestack.razorpay.cas.admin

# TODO To be removed from admin service
hsm:
  enabled_gateway: "NoOpHSM"
  gateway:
    luna:
      ip: "127.0.0.1"
      port: 8080
      timeout: 1
#
## TODO To be removed from admin service
task:
  scheduler:
    corePoolSize: 5
    maxPoolSize: 10
    keepAliveTime: 60000 #mili


admin-metadata:
  supported-message-versions: ["2.2.0"]
  iso-country-code: [4,248,8,12,16,20,24,660,10,28,32,51,533,36,40,31,44,48,50,52,112,56,84,204,60,64,68,70,72,74,76,92,86,96,100,854,108,116,120,124,132,136,140,148,152,156,344,446,162,166,170,174,178,180,184,188,384,191,192,196,203,
                     208,262,212,214,218,818,222,226,232,233,231,238,234,242,246,250,254,258,260,266,270,268,276,288,292,300,304,308,312,316,320,831,324,624,328,332,334,336,340,348,352,356,360,364,368,372,833,376,380,388,392,832,400,
                     398,404,296,408,410,414,417,418,428,422,426,430,434,438,440,442,807,450,454,458,462,466,470,584,474,478,480,175,484,583,498,492,496,499,500,504,508,104,516,520,524,528,530,540,554,558,562,566,570,574,580,578,512,
                     586,585,275,591,598,600,604,608,612,616,620,630,634,638,642,643,646,652,654,659,662,663,666,670,882,674,678,682,686,688,690,694,702,703,705,90,706,710,239,728,724,144,736,740,744,748,752,756,760,158,762,834,764,
                     626,768,772,776,780,788,792,795,796,798,800,804,784,826,840,581,858,860,548,862,704,850,876,732,887,894,716]
  supported-timezone: ["GMT", "UTC"]








