app:
  acs:
    referenceNumber: "3DS_LOA_ACS_UTSB_020100_00009"

metrics:
  export:
    prometheus:
      enabled: true

hsm:
  enabled_gateway: "NoOpHSM"
  gateway:
    luna:
      ip: "127.0.0.1"
      port: 8080
      timeout: 1