app:
  acs:
    referenceNumber: "99995678901234567890"

management:
  prometheus:
    metrics:
      export:
        enabled: true

hsm:
  enabled_gateway: "NoOpHSM"
  gateway:
    luna:
      ip: "127.0.0.1"
      port: 8080
      timeout: 1


external-libs:
  security:
    SecurityModuleAWS:
      enabled: false # permitted values are Boolean - "true" or "false"

