app:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${ACS_MYSQL_HOST}:${ACS_MYSQL_PORT}/${ACS_MYSQL_DATABASE}
    username: ${ACS_MYSQL_USER}
    password: ${ACS_MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: "file:/opt/card-auth-server/cas-acs/bin/monitoring/monitor-properties.yaml"