app:
  port: 8080
  hostname: https://ec2-52-66-119-35.ap-south-1.compute.amazonaws.com
  acs:
    referenceNumber: "12345678901234567890"
    timeout:
      challengeRequest:  10 #sec
      challengeCompletion: 600 #sec

test:
  enable : true
  attemptedRange:
    start: 7654350700000000
    end: 7654350799999999

spring:
  datasource:
    url: jdbc:mysql://${ACS_MYSQL_HOST}:${ACS_MYSQL_PORT}/${ACS_MYSQL_DATABASE}
    username: ${ACS_MYSQL_USER}
    password: ${ACS_MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
