# use while deployment -Dspring.profiles.active=local This will load the application.properties and the application-local.properties with the latter overriding properties from the first.
app:
  port: 8080
  hostname: http://localhost:8080
  java:
    home: ${JAVA_HOME}
    cacerts: ${CACERTS_PATH:}
  acs:
    referenceNumber: "12345678901234567890"
    operatorId:
      visa: 123456789012345
      mastercard: 123456789012345
      amex: 123456789012345
    timeout:
      challengeRequest: 30 #sec 
      challengeCompletion: 600 #sec
      challengeValidation: 180 #sec

test:
  enable : false
  attemptedRange:
    start: 4016000000000010
    end: 4016000000000020

notification:
  sms:
    enabledChannel: "dummy-sms-server"
  email:
    enabledChannel: "dummy-email-server"
    simpleSMTP:
      host: your-smtp-server.com
      port: 587

otp:
  sms:
    templateName: acs.sms.otp.sample
  email:
    from: acs@bank.com
    templateName: acs.email.otp.sample
    subjectText:  "Verification code"

gateway:
  services:
    VISA_DS:
      mock: true
      url: https://sample-ds.com
      useSSL: false
      connectTimeout: 5000
      responseTimeout: 5000
      keyStore:
        path: ${VISA_DS_KEYSTORE_PATH:}
        password: ${VISA_DS_KEYSTORE_PASSWORD:}
      trustStore:
        path: ${VISA_DS_TRUSTSTORE_PATH:}
        password: ${VISA_DS_TRUSTSTORE_PASSWORD:changeit}
      retryable:
        maxAttempts: 2
        backOffPeriod: 1000   #ms
    MASTERCARD_DS:
      mock: true
      url: https://sample-ds.com
      useSSL: false
      connectTimeout: 5000
      responseTimeout: 5000
      keyStore:
        path: ${MASTERCARD_DS_KEYSTORE_PATH:}
        password: ${MASTERCARD_DS_KEYSTORE_PASSWORD:}
      trustStore:
        path: ${MASTERCARD_DS_TRUSTSTORE_PATH:}
        password: ${MASTERCARD_DS_TRUSTSTORE_PASSWORD:changeit}
      retryable:
        maxAttempts: 2
        backOffPeriod: 1000
    UL_TEST_PORTAL: #needed to testing portal, please keep mock as true in production
      mock: true
      url: https://simulator-mutual-3ds.selftestplatform.com/v2.2.0/info/project_id
      useSSL: false
      connectTimeout: 5000
      responseTimeout: 5000
      keyStore:
        path: ${UL_TEST_PORTAL_KEYSTORE_PATH:}
        password: ${UL_TEST_PORTAL_KEYSTORE_PASSWORD:}
      trustStore:
        path: ${UL_TEST_PORTAL_TRUSTSTORE_PATH:}
        password: ${UL_TEST_PORTAL_TRUSTSTORE_PASSWORD:changeit}
      retryable:
        maxAttempts: 1
        backOffPeriod: 1000


spring:
  application:
    name: Card Auth Server ACS
  datasource:
    url: jdbc:mysql://${ACS_MYSQL_HOST:localhost}:${ACS_MYSQL_PORT:3306}/${ACS_MYSQL_DATABASE:cas_db}
    username: ${ACS_MYSQL_USER:root}
    password: ${ACS_MYSQL_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics", "info" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true         # needs security review, secure end point
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: false
  graphite:
    metrics:
      export:
        enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
    org.freedomfinancestack: INFO
#    org.hibernate.type.descriptor.sql: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

swagger:
  contact-name: Freedom Finance Stack
  contact-mail: contact@freedomfinancestack.org
  app-name: Card Auth Server ACS
  app-description: "Card Auth Server ACS"
  app-version: 1.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: org.freedomfinancestack.razorpay.cas.acs

hsm:
  enabled_gateway: "NoOpHSM"
  gateway:
    luna:
      ip: "127.0.0.1"
      port: 8080
      timeout: 1

auth-value:
  master-card-acs-key: ${MC_ACS_KEY:B039878C1F96D212F509B2DC4CC8CD1BB039878C1F96D212F509B2DC4CC8CD1B}

task:
  scheduler:
    corePoolSize: 5
    maxPoolSize: 10
    keepAliveTime: 60000 #mili

external-libs:
  security:
    SecurityModuleAWS:
      enabled: false
    SecurityModuleAzure:
      enabled: false
  request-parsing:
    RequestParsingModuleAWS:
      enabled: false

institution-ui:
  institution-url: "https://ffs.acs.com/acs/resources/images/"
  institution-css-url: "https://ffs.acs.com/acs/resources/css/stylesEFT.css"
  medium-logo: "medium_image.png"
  high-logo: "high_image.png"
  extra-high-logo: "extra_high_image.png"
  network-ui-config:
    VISA:
      medium-ps: "medium_visa.png"
      high-ps: "high_visa.png"
      extra-high-ps: "extra_high_visa.png"
      html-template-otp: "<!DOCTYPE HTML PUBLIC ''-//W3C//DTD HTML 4.01//EN'' ''http://www.w3.org/TR/html4/strict.dtd''><html lang=''en''><head><meta http-equiv=''x-ua-compatible'' content=''IE=Edge''><meta http-equiv=''Cache-Control'' content=''no cache''><meta http-equiv=''Pragma'' content=''no cache''><meta http-equiv=''Expires'' content=''0''><meta http-equiv=''content-type'' content=''text/html; charset=utf-8''><meta name=''viewport''	content=''width=device-width, initial-scale=1, maximum-scale=1.0'' /><link href=''stylesheet.css'' rel=''stylesheet'' /><style>.button-green {	outline: none;	font-weight: bold;	border: none;	color: #0d0d0d;	height: 30px;	width: 246px;	margin-left: 10px;	background-color: #ebeae6;}.button {outline: none;	font-weight: bold;	border: none;	color: #0d0d0d;	height: 30px;	width: 246px;	margin-left: 10px;	background-color: #fff;}.container {border: none;}</style><script>	function showAndroidToast(){var otp = document.challengeForm.txnotp.value; android.showToast(otp);	}</script> <script> function showAndroidCancel(){ android.cancelClicked(); }</script> <script> function showAndroidToast1(){ android.showToast1(); }</script></head><body bgcolor=''#ffffff'' marginheight=''0'' marginwidth=''0'' leftmargin=''0''	topmargin=''0''><div id=''otp''><div style=''display: inline;''><form action=''sendCRES'' name=''challengeForm'' method=''post''><table border=''0'' cellspacing=''1'' cellpadding=''1'' width=''290'' align=''center'' height=''375'' valign=''middle'' class=''container payer-form''><tr><td colspan=''2'' valign=''top''><table width=''100%%''><tr><tr><td width=''20%%'' align=''left''><img src=INSTITUTION_LOGO border=''0'' height=''50px'' width=''120px''></td><td width=''20%%'' align=''right''><img src=PS_LOGO border=''0'' height=''50px'' width=''90px''></td></tr></tr></table></td></tr><tr><td colspan=''2''><div style=''text-align: center;''><b>Enter your 3D Secure OTP</b></div></td></tr><tr><td colspan=''2''><div style=''text-align: justify; margin-left: 10px; margin-right: 10px''><font size=''2'' color=''black''>We have been sent an OTP (One Time Password) on your register mobile number ending in LAST_FOUR_DIGIT_MOBILE_NUMBER.</font></div></td></tr> <div style=''display: inline;''> <tr> <td colspan=''2''> <tr> <tr> <td width=''20%%'' align=''right''><font size=''2'' color=''black'' style=''margin-right: 5px''>Enter OTP</font></td> <td width=''20%%'' align=''left''><input type=''password'' value='' id=''txnotp'' name=''txnotp'' style=''border-radius: 0; width: 80px; height: 25px; margin-left: 5px''> </td> </tr> </tr></td></tr></div><div style=''display: inline;''> <tr> <td colspan=''2''> <tr> <tr> <td width=''20%%'' align=''left''><input type=''submit'' value=''Submit'' class=''button-green'' onclick=''showAndroidToast()'' style=''border-radius: 0; width: 80px; height: 25px; margin-left: 200px''/></td> <td width=''20%%'' align=''right''><input type=''submit'' value=''Cancel'' class=''button-green'' onclick=''showAndroidCancel()'' style=''border-radius: 0; width: 100px; height: 25px;margin-right: 160px''/></td> </tr> </tr> </div><div style=''display: inline;''> <tr> <td colspan=''2''> <tr> <tr> <td width=''20%%'' align=''left''><font size=''2'' color=''black'' style=''margin-left: 130px''>Did not recieve an OTP?</td> <td width=''20%%'' align=''right''><input type=''submit'' value=''Resend OTP'' class=''button-green'' onclick=''showAndroidToast1()'' style=''border-radius: 0; width: 100px; height: 25px; margin-right: 150px''/> </td> </tr> </tr> </div>  <tr> <td colspan=''2''><font size=''2'' color=''black'' style=''margin-left: 120px''>This page will automatically timeout after 3 minutes</td> </tr> </table></form></div></div></body></html>"
    MASTERCARD:
      medium-ps: "medium_mc.png"
      high-ps: "high_mc.png"
      extra-high-ps: "extra_high_mc.png"
      html-template-otp: "<!DOCTYPE HTML PUBLIC ''-//W3C//DTD HTML 4.01//EN'' ''http://www.w3.org/TR/html4/strict.dtd''><html lang=''en''><head><meta http-equiv=''x-ua-compatible'' content=''IE=Edge''><meta http-equiv=''Cache-Control'' content=''no cache''><meta http-equiv=''Pragma'' content=''no cache''><meta http-equiv=''Expires'' content=''0''><meta http-equiv=''content-type'' content=''text/html; charset=utf-8''><meta name=''viewport''	content=''width=device-width, initial-scale=1, maximum-scale=1.0'' /><link href=''stylesheet.css'' rel=''stylesheet'' /><style>.button-green {	outline: none;	font-weight: bold;	border: none;	color: #0d0d0d;	height: 30px;	width: 246px;	margin-left: 10px;	background-color: #ebeae6;}.button {outline: none;	font-weight: bold;	border: none;	color: #0d0d0d;	height: 30px;	width: 246px;	margin-left: 10px;	background-color: #fff;}.container {border: none;}</style><script>	function showAndroidToast(){var otp = document.challengeForm.txnotp.value; android.showToast(otp);	}</script> <script> function showAndroidCancel(){ android.cancelClicked(); }</script> <script> function showAndroidToast1(){ android.showToast1(); }</script></head><body bgcolor=''#ffffff'' marginheight=''0'' marginwidth=''0'' leftmargin=''0''	topmargin=''0''><div id=''otp''><div style=''display: inline;''><form action=''sendCRES'' name=''challengeForm'' method=''post''><table border=''0'' cellspacing=''1'' cellpadding=''1'' width=''290'' align=''center'' height=''375'' valign=''middle'' class=''container payer-form''><tr><td colspan=''2'' valign=''top''><table width=''100%%''><tr><tr><td width=''20%%'' align=''left''><img src=INSTITUTION_LOGO border=''0'' height=''50px'' width=''120px''></td><td width=''20%%'' align=''right''><img src=PS_LOGO border=''0'' height=''50px'' width=''90px''></td></tr></tr></table></td></tr><tr><td colspan=''2''><div style=''text-align: center;''><b>Enter your 3D Secure OTP</b></div></td></tr><tr><td colspan=''2''><div style=''text-align: justify; margin-left: 10px; margin-right: 10px''><font size=''2'' color=''black''>We have been sent an OTP (One Time Password) on your register mobile number ending in LAST_FOUR_DIGIT_MOBILE_NUMBER.</font></div></td></tr> <div style=''display: inline;''> <tr> <td colspan=''2''> <tr> <tr> <td width=''20%%'' align=''right''><font size=''2'' color=''black'' style=''margin-right: 5px''>Enter OTP</font></td> <td width=''20%%'' align=''left''><input type=''password'' value='' id=''txnotp'' name=''txnotp'' style=''border-radius: 0; width: 80px; height: 25px; margin-left: 5px''> </td> </tr> </tr></td></tr></div><div style=''display: inline;''> <tr> <td colspan=''2''> <tr> <tr> <td width=''20%%'' align=''left''><input type=''submit'' value=''Submit'' class=''button-green'' onclick=''showAndroidToast()'' style=''border-radius: 0; width: 80px; height: 25px; margin-left: 200px''/></td> <td width=''20%%'' align=''right''><input type=''submit'' value=''Cancel'' class=''button-green'' onclick=''showAndroidCancel()'' style=''border-radius: 0; width: 100px; height: 25px;margin-right: 160px''/></td> </tr> </tr> </div><div style=''display: inline;''> <tr> <td colspan=''2''> <tr> <tr> <td width=''20%%'' align=''left''><font size=''2'' color=''black'' style=''margin-left: 130px''>Did not recieve an OTP?</td> <td width=''20%%'' align=''right''><input type=''submit'' value=''Resend OTP'' class=''button-green'' onclick=''showAndroidToast1()'' style=''border-radius: 0; width: 100px; height: 25px; margin-right: 150px''/> </td> </tr> </tr> </div>  <tr> <td colspan=''2''><font size=''2'' color=''black'' style=''margin-left: 120px''>This page will automatically timeout after 3 minutes</td> </tr> </table></form></div></div></body></html>"


