# use while deployment -Dspring.profiles.active=local This will load the application.properties and the application-local.properties with the latter overriding properties from the first.
app:
  port: 8080
  hostname: http://localhost:8080
  java:
    home: ${JAVA_HOME}
    cacerts: ${CACERTS_PATH:}
  acs:
    referenceNumber: "12345678901234567890"
    operatorId:
      visa: 123456789012345
      mastercard: 123456789012345
      amex: 123456789012345
    timeout:
      challengeRequest: 30 #sec
      challengeCompletion: 600 #sec
      challengeValidation: 180 #sec

test:
  enable : false
  attemptedRange:
    start: 4016000000000010
    end: 4016000000000020

notification:
  sms:
    enabledChannel: "dummy-sms-server"
  email:
    enabledChannel: "dummy-email-server"
    simpleSMTP:
      host: your-smtp-server.com
      port: 587

otp:
  sms:
    templateName: acs.sms.otp.sample
  email:
    from: acs@bank.com
    templateName: acs.email.otp.sample
    subjectText:  "Verification code"

gateway:
  services:
    VISA_DS:
      mock: true
      url: https://sample-ds.com
      useSSL: false
      connectTimeout: 5000
      responseTimeout: 5000
      keyStore:
        path: ${VISA_DS_KEYSTORE_PATH:}
        password: ${VISA_DS_KEYSTORE_PASSWORD:}
      trustStore:
        path: ${VISA_DS_TRUSTSTORE_PATH:}
        password: ${VISA_DS_TRUSTSTORE_PASSWORD:changeit}
      retryable:
        maxAttempts: 2
        backOffPeriod: 1000   #ms
    MASTERCARD_DS:
      mock: true
      url: https://sample-ds.com
      useSSL: false
      connectTimeout: 5000
      responseTimeout: 5000
      keyStore:
        path: ${MASTERCARD_DS_KEYSTORE_PATH:}
        password: ${MASTERCARD_DS_KEYSTORE_PASSWORD:}
      trustStore:
        path: ${MASTERCARD_DS_TRUSTSTORE_PATH:}
        password: ${MASTERCARD_DS_TRUSTSTORE_PASSWORD:changeit}
      retryable:
        maxAttempts: 2
        backOffPeriod: 1000
    UL_TEST_PORTAL: #needed to testing portal, please keep mock as true in production
      mock: true
      url: https://simulator-mutual-3ds.selftestplatform.com/v2.2.0/info/project_id
      useSSL: false
      connectTimeout: 5000
      responseTimeout: 5000
      keyStore:
        path: ${UL_TEST_PORTAL_KEYSTORE_PATH:}
        password: ${UL_TEST_PORTAL_KEYSTORE_PASSWORD:}
      trustStore:
        path: ${UL_TEST_PORTAL_TRUSTSTORE_PATH:}
        password: ${UL_TEST_PORTAL_TRUSTSTORE_PASSWORD:changeit}
      retryable:
        maxAttempts: 1
        backOffPeriod: 1000


spring:
  application:
    name: Card Auth Server ACS
  datasource:
    url: jdbc:mysql://${ACS_MYSQL_HOST:localhost}:${ACS_MYSQL_PORT:3306}/${ACS_MYSQL_DATABASE:cas_db}
    username: ${ACS_MYSQL_USER:root}
    password: ${ACS_MYSQL_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics", "info" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true         # needs security review, secure end point
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: false
  graphite:
    metrics:
      export:
        enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
    org.freedomfinancestack: INFO
#    org.hibernate.type.descriptor.sql: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

swagger:
  contact-name: Freedom Finance Stack
  contact-mail: contact@freedomfinancestack.org
  app-name: Card Auth Server ACS
  app-description: "Card Auth Server ACS"
  app-version: 1.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: org.freedomfinancestack.razorpay.cas.acs

hsm:
  enabled_gateway: "NoOpHSM"
  gateway:
    luna:
      ip: "127.0.0.1"
      port: 8080
      timeout: 1

auth-value:
  master-card-acs-key: ${MC_ACS_KEY:B039878C1F96D212F509B2DC4CC8CD1BB039878C1F96D212F509B2DC4CC8CD1B}

task:
  scheduler:
    corePoolSize: 5
    maxPoolSize: 10
    keepAliveTime: 60000 #mili

external-libs:
  security:
    SecurityModuleAWS:
      enabled: false
    SecurityModuleAzure:
      enabled: false
  request-parsing:
    RequestParsingModuleAWS:
      enabled: false

institution-ui:
  institution-url: "https://ffs.acs.com/acs/resources/images/"
  institution-css-url: ${INSTITUTION_CSS_URL:"https://EMV3DS/challenge/css/stylesEFT.css"}
  medium-logo: "medium_image.png"
  high-logo: "high_image.png"
  extra-high-logo: "extra_high_image.png"
  network-ui-config:
    VISA:
      medium-ps: "medium_visa.png"
      high-ps: "high_visa.png"
      extra-high-ps: "extra_high_visa.png"
      html-template-otp: "<!DOCTYPE html><html lang='en'><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>    <meta http-equiv='x-ua-compatible' content='IE=Edge'>    <meta http-equiv='Cache-Control' content='no cache'>    <meta http-equiv='Pragma' content='no cache'>    <meta http-equiv='Expires' content='0'>        <meta name='viewport' content='width=device-width, initial-scale=1'><title>INSTITUTION_NAME</title><link href='INSTITUTION_CSS_URL' rel='stylesheet'><script>function showAndroidToast(){var otp = document.challengeForm.txnotp.value; android.showToast(otp);}</script> <script> function showAndroidCancel(){ android.cancelClicked(); }</script> <script> function showAndroidToast1(){ android.showToast1(); }</script>  </head><body bgcolor='#ffffff' marginheight='0' marginwidth='0' leftmargin='0' topmargin='0' onload='setDisplayUI()'><form action='sendCRES' name='challengeForm' method='post'><div class='main'>      <div class='header'>            <div>                <img src='INSTITUTION_LOGO' id='img2' style='margin-top: -10px;' width='130' alt='Central Africa Building Society Ltd '>                          </div><div class='cabsPay'>                <img src='PS_LOGO' id='img1' alt='logo' width='100'>            </div>                     </div>      <div class='textHading'>          <h3>Enter your 3D Secure OTP</h3>      </div>      <div class='textMassage'>          <span>              An OTP (One-Time Password) has been sent to your registered mobile number ending in LAST_FOUR_DIGIT_MOBILE_NUMBER.           </span><br>          <br>          <span>              Please enter the OTP in the space provided below to authenticate this              transaction. This information is not shared with the merchant          </span>      </div>      <div class='cardDetails'>          <div class='cardDetailsHeading'>              <span class='textBold'>Card Number:</span> <br>              <span class='textBold'>Merchant:</span> <br>              <span class='textBold'>Amount:</span> <br>              <span class='textBold'>Date:</span> <br>          </div>          <div>              <span>MASKED_CARD_NUMBER</span> <br>              <span>MERCHANT_NAME</span><br>              <span>AMOUNT_WITH_CURRENCY</span><br>              <span>TRANSACTION_DATE</span><br>          </div>      </div>      <div class='inputRow'>          <div class='inputRowText textBold'>Enter OTP:</div>          <div class='form-group'>              <input type='Password' class='otpInput' name='txnotp' id='txnotp'>          </div>      </div>     <div class='textMassage' style='text-align: center;align: center;'> </div>      <div class='buttonRow'>          <div><input type='submit' value='Submit' class='button' onclick='showAndroidToast()'/></div>          <div class='cancelBtn'><button class='button' type='button' onclick='showAndroidCancel()'>Cancel</button></div>      </div>      <div class='reSendOtp'>          <div class='resendText'><span>Did not receive an OTP?</span></div>          <div class='resendDiv'> <button class='resendBtn' type='button' onclick='showAndroidToast1()'>Resend OTP</button></div>      </div>         <div class='footer'>          <span>              OTPs are secret! Do not disclose it to anyone. The bank will never              ask you for your OTP.          </span><br><br>          <span>              This page will automatically timeout after INSTITUTION_TIMEOUT_IN_SECONDS seconds.          </span>      </div></div></form></body></html>"
    MASTERCARD:
      medium-ps: "medium_mc.png"
      high-ps: "high_mc.png"
      extra-high-ps: "extra_high_mc.png"
      html-template-otp: "<!DOCTYPE html><html lang='en'><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>    <meta http-equiv='x-ua-compatible' content='IE=Edge'>    <meta http-equiv='Cache-Control' content='no cache'>    <meta http-equiv='Pragma' content='no cache'>    <meta http-equiv='Expires' content='0'>        <meta name='viewport' content='width=device-width, initial-scale=1'><title>INSTITUTION_NAME</title><link href='INSTITUTION_CSS_URL' rel='stylesheet'><script>function showAndroidToast(){var otp = document.challengeForm.txnotp.value; android.showToast(otp);}</script> <script> function showAndroidCancel(){ android.cancelClicked(); }</script> <script> function showAndroidToast1(){ android.showToast1(); }</script>  </head><body bgcolor='#ffffff' marginheight='0' marginwidth='0' leftmargin='0' topmargin='0' onload='setDisplayUI()'><form action='sendCRES' name='challengeForm' method='post'><div class='main'>      <div class='header'>            <div>                <img src='INSTITUTION_LOGO' id='img2' style='margin-top: -10px;' width='130' alt='Central Africa Building Society Ltd '>                          </div><div class='cabsPay'>                <img src='PS_LOGO' id='img1' alt='logo' width='100'>            </div>                     </div>      <div class='textHading'>          <h3>Enter your 3D Secure OTP</h3>      </div>      <div class='textMassage'>          <span>              An OTP (One-Time Password) has been sent to your registered mobile number ending in LAST_FOUR_DIGIT_MOBILE_NUMBER.           </span><br>          <br>          <span>              Please enter the OTP in the space provided below to authenticate this              transaction. This information is not shared with the merchant          </span>      </div>      <div class='cardDetails'>          <div class='cardDetailsHeading'>              <span class='textBold'>Card Number:</span> <br>              <span class='textBold'>Merchant:</span> <br>              <span class='textBold'>Amount:</span> <br>              <span class='textBold'>Date:</span> <br>          </div>          <div>              <span>MASKED_CARD_NUMBER</span> <br>              <span>MERCHANT_NAME</span><br>              <span>AMOUNT_WITH_CURRENCY</span><br>              <span>TRANSACTION_DATE</span><br>          </div>      </div>      <div class='inputRow'>          <div class='inputRowText textBold'>Enter OTP:</div>          <div class='form-group'>              <input type='Password' class='otpInput' name='txnotp' id='txnotp'>          </div>      </div>     <div class='textMassage' style='text-align: center;align: center;'> </div>      <div class='buttonRow'>          <div><input type='submit' value='Submit' class='button' onclick='showAndroidToast()'/></div>          <div class='cancelBtn'><button class='button' type='button' onclick='showAndroidCancel()'>Cancel</button></div>      </div>      <div class='reSendOtp'>          <div class='resendText'><span>Did not receive an OTP?</span></div>          <div class='resendDiv'> <button class='resendBtn' type='button' onclick='showAndroidToast1()'>Resend OTP</button></div>      </div>         <div class='footer'>          <span>              OTPs are secret! Do not disclose it to anyone. The bank will never              ask you for your OTP.          </span><br><br>          <span>              This page will automatically timeout after INSTITUTION_TIMEOUT_IN_SECONDS seconds.          </span>      </div></div></form></body></html>"


