# use while deployment -Dspring.profiles.active=local This will load the application.properties and the application-local.properties with the latter overriding properties from the first.
app:
  port: 8080
  hostname: http://localhost:8080
  java:
    home: ${JAVA_HOME}
    cacerts: ${CACERTS_PATH:}
  acs:
    referenceNumber: "12345678901234567890"
    operatorId:
      visa: 123456789012345
      mastercard: 123456789012345
      amex: 123456789012345
    timeout:
      challengeRequest: 30 #sec
      challengeCompletion: 600 #sec
      challengeValidation: 180 #sec
      decoupledChallengeCompletion: 600 #sec
      decoupledAuthDelay : 5 #sec

test:
  enable-decryption-encryption: true
  enable : false
  attemptedRange:
    start: 4016000000000010
    end: 4016000000000020

notification:
  sms:
    enabledChannel: "dummy-sms-server"
  email:
    enabledChannel: "dummy-email-server"
    simpleSMTP:
      host: your-smtp-server.com
      port: 587

otp:
  sms:
    templateName: acs.sms.otp.sample
  email:
    from: acs@bank.com
    templateName: acs.email.otp.sample
    subjectText:  "Verification code"

gateway:
  services:
    VISA_DS:
      mock: true
      url: https://sample-ds.com
      useSSL: false
      connectTimeout: 5000
      responseTimeout: 5000
      keyStore:
        path: ${VISA_DS_KEYSTORE_PATH:}
        password: ${VISA_DS_KEYSTORE_PASSWORD:}
      trustStore:
        path: ${VISA_DS_TRUSTSTORE_PATH:}
        password: ${VISA_DS_TRUSTSTORE_PASSWORD:changeit}
      retryable:
        maxAttempts: 2
        backOffPeriod: 1000   #ms
    MASTERCARD_DS:
      mock: true
      url: https://sample-ds.com
      useSSL: false
      connectTimeout: 5000
      responseTimeout: 5000
      keyStore:
        path: ${MASTERCARD_DS_KEYSTORE_PATH:}
        password: ${MASTERCARD_DS_KEYSTORE_PASSWORD:}
      trustStore:
        path: ${MASTERCARD_DS_TRUSTSTORE_PATH:}
        password: ${MASTERCARD_DS_TRUSTSTORE_PASSWORD:changeit}
      retryable:
        maxAttempts: 2
        backOffPeriod: 1000
    UL_TEST_PORTAL: #needed to testing portal, please keep mock as true in production
      mock: true
      url: https://simulator-mutual-3ds.selftestplatform.com/v2.2.0/info/project_id
      useSSL: false
      connectTimeout: 5000
      responseTimeout: 30000
      keyStore:
        path: ${UL_TEST_PORTAL_KEYSTORE_PATH:}
        password: ${UL_TEST_PORTAL_KEYSTORE_PASSWORD:}
      trustStore:
        path: ${UL_TEST_PORTAL_TRUSTSTORE_PATH:}
        password: ${UL_TEST_PORTAL_TRUSTSTORE_PASSWORD:changeit}
      retryable:
        maxAttempts: 1
        backOffPeriod: 1000


spring:
  application:
    name: Card Auth Server ACS
  datasource:
    url: jdbc:mysql://${ACS_MYSQL_HOST:localhost}:${ACS_MYSQL_PORT:3306}/${ACS_MYSQL_DATABASE:cas_db}
    username: ${ACS_MYSQL_USER:root}
    password: ${ACS_MYSQL_PASSWORD:Mysql@123}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics", "info" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true         # needs security review, secure end point
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: false
  graphite:
    metrics:
      export:
        enabled: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
    org.freedomfinancestack: INFO
#    org.hibernate.type.descriptor.sql: TRACE
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

swagger:
  contact-name: Freedom Finance Stack
  contact-mail: contact@freedomfinancestack.org
  app-name: Card Auth Server ACS
  app-description: "Card Auth Server ACS"
  app-version: 1.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: org.freedomfinancestack.razorpay.cas.acs

hsm:
  enabled_gateway: "NoOpHSM"
  gateway:
    luna:
      ip: "127.0.0.1"
      port: 8080
      timeout: 1

auth-value:
  master-card-acs-key: ${MC_ACS_KEY:B039878C1F96D212F509B2DC4CC8CD1BB039878C1F96D212F509B2DC4CC8CD1B}

task:
  scheduler:
    corePoolSize: 5
    maxPoolSize: 10
    keepAliveTime: 60000 #mili

external-libs:
  security:
    SecurityModuleAWS:
      enabled: false
    SecurityModuleAzure:
      enabled: false
  request-parsing:
    RequestParsingModuleAWS:
      enabled: false

institution-ui:
  institution-url: https://ffs.acs.com/acs/resources/images/
  institution-css-url: ${INSTITUTION_CSS_URL:https://EMV3DS/challenge}
  html-page-timer: 180 #seconds
  medium-logo: "medium_image.png"
  high-logo: "high_image.png"
  extra-high-logo: "extra_high_image.png"
  html-otp-template: "appAcsOtp"
  network-ui-config:
    VISA:
      medium-ps: "medium_visa.png"
      high-ps: "high_visa.png"
      extra-high-ps: "extra_high_visa.png"
    MASTERCARD:
      medium-ps: "medium_mc.png"
      high-ps: "high_mc.png"
      extra-high-ps: "extra_high_mc.png"


