name: Build
on: [push]
jobs:
  cancel:
    runs-on: [self-hosted]
    name: Cancel Previous Runs
    if: always()
    steps:
      - uses: styfle/cancel-workflow-action@d57d93c3a8110b00c3a2c0b64b8516013c9fd4c9
        if: github.ref != 'refs/heads/master'
        name: cancel old workflows
        id: cancel
        with:
          access_token: ${{ github.token }}
      - if: github.ref == 'refs/heads/master'
        name: Don't cancel old workflows
        id: dont_cancel
        run: |
          echo "Don't cancel old workflow"
  build-image:
    #    change to ubuntu and remove maven installation
    runs-on: [self-hosted]
    needs: [cancel]
    continue-on-error: false
    name: Build Image
    env:
      REPO_NAME: razorpay/secure-auth-server
      APP_NAME: secure-auth-server
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt-hotspot'
          cache: 'maven'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.6

      - name: Clean, Compile, Test and  Package
        run: mvn -B clean install

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Push
        uses: docker/build-push-action@v4
        with:
          tags: c.rzp.io/razorpay/secure-auth-server:${{ github.sha }}
          context: .
          file: ./scripts/deployment/dockerconf/secure-auth-server/Dockerfile
          push: true
          secrets: |
            git_token=${{ secrets.GIT_TOKEN }}
          build-args: |
            GIT_ACTOR=${{ github.actor }}'
      - name: Update Build Status Succeeded
        if: success()
        run: |
          echo 'Status check has passed!'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "success" , "context" : "'github/${APP_NAME}-status-check'" , "description" : "'github/${APP_NAME}-status-check'", "target_url" : "'https://github.com/${REPO_NAME}'" }' \
          https://api.github.com/repos/${REPO_NAME}/statuses/${GITHUB_SHA}
          exit 0