name: Docker Build and Push to DockerHub

on:
  push:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    continue-on-error: false
    name: Build Image
    env:
      REPO_NAME: razorpay/freedomfinancestack
      APP_NAME: card-auth-server
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Clean, Compile, Test and  Package
        run: mvn -B clean install

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Push
        uses: docker/build-push-action@v4
        with:
          tags: razorpay/freedomfinancestack:challenge-ul-portal-testing
          context: .
          file: ./scripts/deployment/dockerconf/card-auth-server-acs/Dockerfile
          push: true